name: 🐞 Bug Report
description: Report a problem with the contract, auto-relay, or listener
title: "[BUG]: "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Please describe the bug you encountered with as much detail as possible.

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What were you doing when it occurred?
      placeholder: Describe the issue clearly...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: List the steps to reliably recreate the issue.
      placeholder: |
        1. Go to '...'
        2. Run '...'
        3. See error
    validations:
      required: false

  - type: input
    id: environment
    attributes:
      label: Environment (optional)
      placeholder: OS, Node version, ethers.js version...
