name: Project Sync

on:
  issues:
    types: [opened, edited, closed, reopened, assigned]
  pull_request:
    types: [opened, closed, reopened]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Move issue to In Progress when assigned
        if: github.event_name == 'issues' && github.event.action == 'assigned'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue = context.payload.issue;
            const projectId = "PVT_kwDOHNg3J84Ab"; // Replace with your project ID
            const columnName = "In Progress";

            const { data: projects } = await github.rest.projects.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo
            });

            for (const project of projects) {
              if (project.name === "RelayNoir Project") {
                const columns = await github.rest.projects.listColumns({ project_id: project.id });
                const targetColumn = columns.data.find(col => col.name === columnName);
                if (targetColumn) {
                  await github.rest.projects.createCard({
                    column_id: targetColumn.id,
                    content_id: issue.id,
                    content_type: "Issue"
                  });
                }
              }
            }